export const projects = [
    { id: 1, title: "A Graphical-Authentication-User-System-Experience (GAUSX)", language: "PHP & JavaScript", animate: "fadeInLeft", image: "images/gaux.PNG", link: "https://www.uhome.com.ng/jonah_gaus", select: "php", iframe: "https://www.youtube.com/embed/3gFlq1XNztY?si=Whzf_iSWxPcLfEjS", description: "This innovative web-based authentication system offers users the option to create a more secure login process by utilizing a combination of graphical and text-based passwords. Studies have indicated that people tend to remember images more effectively than text, and traditional text passwords are susceptible to hacking. By allowing users to select specific images and grid points to use as their graphical passwords, this system aims to provide a higher level of security compared to standard text passwords. This project was developed using HTML, PHP, JavaScript, JQuery, CSS and MySQL." },
    { id: 2, title: "Music Player", language: "NEXT.JS", animate: "fadeInRight", image: "images/umusic.png", link: "https://utmusicplayer.netlify.app/", select: "reactts", iframe: "https://www.youtube.com/embed/your_video_id_here", description: "Introducing an innovative and highly dynamic music player developed with NEXT JS, designed to elevate your listening experience. This advanced music player application offers extensive customization options and a user-friendly interface, making it a joy to navigate. With a comprehensive suite of features, you can effortlessly play your favorite audio tracks and songs. What sets this player apart is its ability to transform the background based on the music currently playing, using the album art to create a visually engaging atmosphere that enhances your enjoyment. As you explore your playlists, you’ll also find detailed descriptions of the artists, giving you insight into their work, along with information about the album release year. This not only enriches your listening experience but also deepens your appreciation for the music. So, sit back, relax, and let this amazing music player transport you into a world of sound and visual delight. Cheers! Listen and enjoy! Introducing a unique and dynamic music player created with React JS. This advanced music player application is fully customizable and user-friendly, featuring all the essential functionalities to play audio and songs. It also changes the background according to the music currently being played, utilizing the album art for an enhanced experience. This adds a great vibe to your listening sessions. Additionally, it provides a brief description of the artist and the album's release year. Cheers! Listen and enjoy!" },
    { id: 3, title: "U Shop", language: "PHP & JS", animate: "fadeInUp", image: "assets/ushop.PNG", link: "https://www.ushop.com.ng", select: "php", iframe: "https://youtube.com/embed/your_video_id_here", description: "This E-Commerce website is built in PHP and primarily focuses on online shopping. The system displays a comprehensive list of products along with their respective prices. Additionally, it allows for the management of product brands. The project is divided into two categories: Admin and Customer. In this web application, customers must register to perform various actions. Once registered, customers can search for products, add items to their cart, and create a wishlist. Each product includes a detailed description, features, and multiple photos. Regarding the checkout process, customers can enter coupon codes for discounts. After completing the checkout procedures, customers can manage their orders from the account section." },
    { id: 4, title: "U Shop 2.0", language: "React TypeScript", animate: "fadeInUp", image: "images/ushop2.PNG", link: "https://ushop-react.netlify.app", select: "reactts", iframe: "https://www.youtube.com/embed/your_video_id_here", description: "Ushop 2.0" },
    { id: 5, title: "InstaVlog", language: "React TypeScript", animate: "fadeInLeft", image: "assets/insta.svg", link: "https://github.com/Djonahuti/instavlog", select: "reactts", iframe: "https://www.youtube.com/embed/your_video_id_here", description: "Explore social media with this user-friendly platform that has a nice look and lots of features. Easily create and explore posts, and enjoy a strong authentication system and quick data fetching using React Query for a smooth user experience" },
    { id: 6, title: "Project 6", language: "React Native", animate: "fadeInRight", image: "assets/uhome.png", link: "#!", select: "reactts", iframe: "https://www.youtube.com/embed/your_video_id_here", description: "My Project Description" },
    { id: 7, title: "Project 7", language: "React Native", animate: "fadeInUp", image: "assets/uhome.png", link: "#!", select: "reactts", iframe: "https://www.youtube.com/embed/your_video_id_here", description: "My Project Description" },
    { id: 8, title: "Project 8", language: "Laravel PHP", animate: "fadeInButtom", image: "assets/uhome.png", link: "#!", select: "php", iframe: "https://www.youtube.com/embed/your_video_id_here", description: "My Project Description" },
    // add more projects here
  ];
  
